import type { Product, ProductImage } from "@/types/product";
import { SIZES } from "@/types/product";
import {
  COTTON_CARE,
  HANDLOOM_CARE,
  SILK_BLEND_CARE,
  MADE_TO_ORDER_SHIPPING_INFO,
  STANDARD_SHIPPING_INFO,
} from "@/lib/mock-data/care-presets";
import { GALLERY_IMAGES } from "@/lib/mock-data/gallery-images";

/** Deterministic per-slug rotation through the real dummy photos, so each product starts on a different one. */
function hashSeed(input: string): number {
  let hash = 0;
  for (let i = 0; i < input.length; i++) hash = (hash * 31 + input.charCodeAt(i)) >>> 0;
  return hash;
}

function images(slug: string, count: number, tone: number): ProductImage[] {
  const start = hashSeed(slug) % GALLERY_IMAGES.length;
  return Array.from({ length: count }, (_, i) => ({
    id: `${slug}-${i + 1}`,
    alt: "",
    tone: Math.min(0.95, Math.max(0.05, tone + i * 0.07)),
    src: GALLERY_IMAGES[(start + i) % GALLERY_IMAGES.length],
  }));
}

export const products: Product[] = [
  {
    id: "p1",
    slug: "handloom-kurta-set",
    name: "Handloom Kurta Set",
    shortDescription: "Hand-woven cotton kurta with matching straight pants.",
    description:
      "A hand-woven cotton kurta set in a soft, breathable weave, finished with a stand collar and side slits for ease of movement. Comes with matching straight-fit pants. The slight texture in the cloth is a signature of the handloom process, not a flaw — no two lengths weave up quite the same.",
    price: 3499,
    images: images("handloom-kurta-set", 4, 0.2),
    category: "Kurta Sets",
    collectionSlugs: ["handloom-stories", "everyday-edit"],
    tags: ["cotton", "handloom", "everyday"],
    isNew: true,
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    supportsCustomSize: true,
    fabric: "100% handloom cotton",
    washCare: HANDLOOM_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Relaxed fit through the body, true to size.",
  },
  {
    id: "p2",
    slug: "kalamkari-print-kurta",
    name: "Kalamkari Print Kurta",
    shortDescription: "Hand block-printed kurta with a rounded hem.",
    description:
      "A single kurta hand block-printed in a traditional kalamkari-inspired motif, cut in a lightly A-lined silhouette with a rounded hem. Wear it over trousers or leggings for an easy, everyday look.",
    price: 2299,
    compareAtPrice: 2799,
    images: images("kalamkari-print-kurta", 4, 0.55),
    category: "Kurta Sets",
    collectionSlugs: ["handloom-stories"],
    tags: ["cotton", "printed", "bestseller"],
    isBestSeller: true,
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    fabric: "Pure cotton, hand block-printed",
    washCare: COTTON_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "A-line fit, true to size.",
  },
  {
    id: "p3",
    slug: "cotton-anarkali",
    name: "Cotton Anarkali",
    shortDescription: "Flared cotton anarkali with covered buttons.",
    description:
      "A floor-grazing anarkali in mid-weight cotton, gathered from the yoke for a full, flattering flare. Covered buttons run along the front placket, finished with a simple round neckline that keeps the focus on the silhouette.",
    price: 4199,
    compareAtPrice: 4999,
    images: images("cotton-anarkali", 5, 0.1),
    category: "Anarkali",
    collectionSlugs: ["contemporary-classics"],
    tags: ["cotton", "anarkali"],
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    supportsCustomSize: true,
    fabric: "Mid-weight cotton",
    washCare: COTTON_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Fitted through the yoke, flared below. Order your usual size.",
  },
  {
    id: "p4",
    slug: "rani-weave-kurta-set",
    name: "Rani Weave Kurta Set",
    shortDescription: "Handwoven kurta set in a rich, saturated weave.",
    description:
      "A handwoven kurta set built on an interlocking weft weave, giving the cloth a subtle shimmer without any embellishment. Paired with matching straight pants and a lightly textured dupatta.",
    price: 5299,
    images: images("rani-weave-kurta-set", 5, 0.75),
    category: "Kurta Sets",
    collectionSlugs: ["festive-edit", "handloom-stories"],
    tags: ["handloom", "festive"],
    isSoldOut: true,
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve", "18\" Sleeve"],
    supportsCustomSize: true,
    fabric: "Handloom cotton-silk blend",
    washCare: SILK_BLEND_CARE,
    shippingInfo: MADE_TO_ORDER_SHIPPING_INFO,
    fitNotes: "Relaxed fit. Runs true to size.",
  },
  {
    id: "p5",
    slug: "everyday-cotton-coord-set",
    name: "Everyday Cotton Co-ord Set",
    shortDescription: "Boxy top and wide-leg pants in washed cotton.",
    description:
      "A two-piece co-ord set — a boxy, cropped top with dropped shoulders paired with wide-leg pants in the same washed cotton. Designed to be worn together or split across your everyday rotation.",
    price: 2899,
    images: images("everyday-cotton-coord-set", 4, 0.3),
    category: "Co-ord Sets",
    collectionSlugs: ["everyday-edit"],
    tags: ["cotton", "coord", "everyday"],
    isNew: true,
    sizes: SIZES,
    fabric: "Washed cotton twill",
    washCare: COTTON_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Boxy, relaxed fit. Size down for a closer fit.",
  },
  {
    id: "p6",
    slug: "festive-handloom-set",
    name: "Festive Handloom Set",
    shortDescription: "Handwoven kurta set with a contrast dupatta.",
    description:
      "A three-piece handloom set for occasions that call for a little more — a fitted kurta, straight pants, and a contrast dupatta with a hand-finished border. Understated construction lets the weave carry the piece.",
    price: 6299,
    images: images("festive-handloom-set", 5, 0.5),
    category: "Kurta Sets",
    collectionSlugs: ["festive-edit"],
    tags: ["handloom", "festive"],
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve", "18\" Sleeve"],
    supportsCustomSize: true,
    fabric: "Handloom cotton, contrast dupatta in silk-blend",
    washCare: SILK_BLEND_CARE,
    shippingInfo: MADE_TO_ORDER_SHIPPING_INFO,
    fitNotes: "Fitted through the bodice. True to size.",
  },
  {
    id: "p7",
    slug: "contemporary-kurta",
    name: "Contemporary Kurta",
    shortDescription: "Minimal straight kurta with side slits.",
    description:
      "A straight-cut kurta pared back to the essentials — clean placket, side slits, no print. Meant to be worn on repeat, styled up or down depending on the day.",
    price: 2199,
    images: images("contemporary-kurta", 3, 0.62),
    category: "Kurta Sets",
    collectionSlugs: ["contemporary-classics"],
    tags: ["cotton", "minimal"],
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    fabric: "Pure cotton",
    washCare: COTTON_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Straight fit, true to size.",
  },
  {
    id: "p8",
    slug: "printed-dupatta-set",
    name: "Printed Dupatta Set",
    shortDescription: "Block-printed kurta and dupatta set.",
    description:
      "A relaxed kurta in a small-scale block print, layered with a matching dupatta finished with hand-rolled edges. Built for warm-weather everydays.",
    price: 2599,
    images: images("printed-dupatta-set", 4, 0.22),
    category: "Dupatta Sets",
    collectionSlugs: ["everyday-edit"],
    tags: ["cotton", "printed"],
    sizes: SIZES,
    fabric: "Pure cotton",
    washCare: COTTON_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Relaxed fit, true to size.",
  },
  {
    id: "p9",
    slug: "ivory-handloom-saree-blouse-set",
    name: "Ivory Handloom Saree Blouse Set",
    shortDescription: "Handloom saree with a fitted blouse piece.",
    description:
      "An ivory handloom saree with a fine self-stripe running through the body, paired with an unstitched blouse piece in a matching weave. Understated enough for both daytime and evening occasions.",
    price: 7499,
    images: images("ivory-handloom-saree-blouse-set", 4, 0.08),
    category: "Saree Sets",
    collectionSlugs: ["handloom-stories", "festive-edit"],
    tags: ["handloom", "saree"],
    isSoldOut: true,
    sizes: SIZES,
    fabric: "Handloom cotton",
    washCare: HANDLOOM_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Blouse piece unstitched — pair with our custom sizing at checkout on request.",
  },
  {
    id: "p10",
    slug: "block-print-straight-kurta",
    name: "Block Print Straight Kurta",
    shortDescription: "Best-selling straight kurta in hand block print.",
    description:
      "Our most-repeated silhouette — a straight kurta in a hand block-printed cotton, cut generously through the body with a simple round neck and elbow-length sleeves.",
    price: 1999,
    compareAtPrice: 2399,
    images: images("block-print-straight-kurta", 4, 0.42),
    category: "Kurta Sets",
    collectionSlugs: ["everyday-edit", "contemporary-classics"],
    tags: ["cotton", "printed", "bestseller"],
    isBestSeller: true,
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    fabric: "Pure cotton, hand block-printed",
    washCare: COTTON_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Relaxed fit, true to size.",
  },
  {
    id: "p11",
    slug: "mul-cotton-anarkali-set",
    name: "Mul Cotton Anarkali Set",
    shortDescription: "Featherweight anarkali set in mul cotton.",
    description:
      "A featherweight mul cotton anarkali with a gathered flare, paired with churidar pants and a soft dupatta with a tasselled edge. Sheer without being sheer where it counts — layered on an inner lining.",
    price: 4899,
    images: images("mul-cotton-anarkali-set", 5, 0.68),
    category: "Anarkali",
    collectionSlugs: ["festive-edit"],
    tags: ["cotton", "anarkali", "festive"],
    isNew: true,
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    supportsCustomSize: true,
    fabric: "Mul cotton with cotton lining",
    washCare: COTTON_CARE,
    shippingInfo: MADE_TO_ORDER_SHIPPING_INFO,
    fitNotes: "Fitted yoke, full flare. True to size.",
  },
  {
    id: "p12",
    slug: "ikat-weave-coord-set",
    name: "Ikat Weave Co-ord Set",
    shortDescription: "Handwoven ikat top and pants set.",
    description:
      "A co-ord set in a handwoven ikat, where the pattern is dyed into the yarn before weaving — giving the soft, slightly blurred edge that defines ikat cloth. Cropped top, straight pants.",
    price: 4599,
    images: images("ikat-weave-coord-set", 4, 0.35),
    category: "Co-ord Sets",
    collectionSlugs: ["contemporary-classics", "handloom-stories"],
    tags: ["handloom", "ikat", "coord"],
    sizes: SIZES,
    sleeveOptions: ["Sleeveless", "3/4 Sleeve", "Full Sleeve"],
    fabric: "Handwoven ikat cotton",
    washCare: HANDLOOM_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Cropped, fitted top. True to size.",
  },
  {
    id: "p13",
    slug: "chanderi-silk-kurta-set",
    name: "Chanderi Silk Kurta Set",
    shortDescription: "Best-selling Chanderi silk kurta with pants.",
    description:
      "A kurta set in Chanderi silk-cotton, prized for its light sheen and papery drape. Cut in a fitted silhouette with a straight hem, paired with matching pants.",
    price: 5799,
    images: images("chanderi-silk-kurta-set", 4, 0.58),
    category: "Kurta Sets",
    collectionSlugs: ["festive-edit"],
    tags: ["silk", "festive", "bestseller"],
    isBestSeller: true,
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    supportsCustomSize: true,
    fabric: "Chanderi silk-cotton blend",
    washCare: SILK_BLEND_CARE,
    shippingInfo: MADE_TO_ORDER_SHIPPING_INFO,
    fitNotes: "Fitted through the body. True to size.",
  },
  {
    id: "p14",
    slug: "linen-blend-straight-kurta",
    name: "Linen Blend Straight Kurta",
    shortDescription: "Breathable linen-cotton kurta for warm days.",
    description:
      "A straight kurta in a linen-cotton blend, chosen for how it softens and breathes with wear. Minimal detailing — a curved hem and a simple placket are the only interruptions.",
    price: 2699,
    images: images("linen-blend-straight-kurta", 3, 0.18),
    category: "Kurta Sets",
    collectionSlugs: ["everyday-edit"],
    tags: ["linen", "everyday"],
    sizes: SIZES,
    sleeveOptions: ["3/4 Sleeve", "Full Sleeve"],
    fabric: "Linen-cotton blend",
    washCare: COTTON_CARE,
    shippingInfo: STANDARD_SHIPPING_INFO,
    fitNotes: "Relaxed fit, true to size.",
  },
];
